# fly.toml app configuration file generated for warbot40k on 2024-11-10T17:25:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'warbot40k'
primary_region = 'mad'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
